/*
 * peripherals.c
 *
 *  Created on: 4. 24, 2026
 *      Author: Nong Jun
 */
 
#include "phaseouts.h"
#include "targets.h"

#define USE_FROCE_LEVEL 1
#define USE_HPWM_LPWM   1

#define DDL_ATMR_FORCE_OUTPUT_AH        DDL_ATMR_FORCE_OUTPUT_CH0
#define DDL_ATMR_FORCE_OUTPUT_AL        DDL_ATMR_FORCE_OUTPUT_CH0N

#define DDL_ATMR_FORCE_OUTPUT_AH_HIGH   DDL_ATMR_CH0_FORCE_OUTPUT_HIGH
#define DDL_ATMR_FORCE_OUTPUT_AL_HIGH   DDL_ATMR_CH0N_FORCE_OUTPUT_HIGH
#define DDL_ATMR_FORCE_OUTPUT_AH_LOW    DDL_ATMR_CH0_FORCE_OUTPUT_LOW
#define DDL_ATMR_FORCE_OUTPUT_AL_LOW    DDL_ATMR_CH0N_FORCE_OUTPUT_LOW

#define DDL_ATMR_FORCE_OUTPUT_BH        DDL_ATMR_FORCE_OUTPUT_CH1
#define DDL_ATMR_FORCE_OUTPUT_BL        DDL_ATMR_FORCE_OUTPUT_CH1N

#define DDL_ATMR_FORCE_OUTPUT_BH_HIGH   DDL_ATMR_CH1_FORCE_OUTPUT_HIGH
#define DDL_ATMR_FORCE_OUTPUT_BL_HIGH   DDL_ATMR_CH1N_FORCE_OUTPUT_HIGH
#define DDL_ATMR_FORCE_OUTPUT_BH_LOW    DDL_ATMR_CH1_FORCE_OUTPUT_LOW
#define DDL_ATMR_FORCE_OUTPUT_BL_LOW    DDL_ATMR_CH1N_FORCE_OUTPUT_LOW


#define DDL_ATMR_FORCE_OUTPUT_CH        DDL_ATMR_FORCE_OUTPUT_CH2
#define DDL_ATMR_FORCE_OUTPUT_CL        DDL_ATMR_FORCE_OUTPUT_CH2N

#define DDL_ATMR_FORCE_OUTPUT_CH_HIGH   DDL_ATMR_CH2_FORCE_OUTPUT_HIGH
#define DDL_ATMR_FORCE_OUTPUT_CL_HIGH   DDL_ATMR_CH2N_FORCE_OUTPUT_HIGH
#define DDL_ATMR_FORCE_OUTPUT_CH_LOW    DDL_ATMR_CH2_FORCE_OUTPUT_LOW
#define DDL_ATMR_FORCE_OUTPUT_CL_LOW    DDL_ATMR_CH2N_FORCE_OUTPUT_LOW

void proportionalBrake()
{
#if USE_FROCE_LEVEL
    DDL_ATMR_CHAN_EnableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_AH);
    DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_AH,DDL_ATMR_FORCE_OUTPUT_AH_LOW);
    DDL_ATMR_CHAN_EnableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_BH);
    DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_BH,DDL_ATMR_FORCE_OUTPUT_BH_LOW);
    DDL_ATMR_CHAN_EnableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_CH);
    DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_CH,DDL_ATMR_FORCE_OUTPUT_CH_LOW);
    
    DDL_ATMR_CHAN_EnableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_AL);
    DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_AL,DDL_ATMR_FORCE_OUTPUT_AL_HIGH);
    DDL_ATMR_CHAN_EnableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_BL);
    DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_BL,DDL_ATMR_FORCE_OUTPUT_BL_HIGH);
    DDL_ATMR_CHAN_EnableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_CL);
    DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_CL,DDL_ATMR_FORCE_OUTPUT_CL_HIGH);
#else
    PHASE_A_GPIO_PORT_HIGH->BRR = PHASE_A_GPIO_HIGH;
    PHASE_B_GPIO_PORT_HIGH->BRR = PHASE_B_GPIO_HIGH;
    PHASE_C_GPIO_PORT_HIGH->BRR = PHASE_C_GPIO_HIGH;
    DDL_GPIO_SetPinMode(PHASE_A_GPIO_PORT_HIGH,PHASE_A_GPIO_HIGH,DDL_GPIO_MODE_OUTPUT);
    DDL_GPIO_SetPinMode(PHASE_B_GPIO_PORT_HIGH,PHASE_B_GPIO_HIGH,DDL_GPIO_MODE_OUTPUT);
    DDL_GPIO_SetPinMode(PHASE_C_GPIO_PORT_HIGH,PHASE_C_GPIO_HIGH,DDL_GPIO_MODE_OUTPUT);
    
    PHASE_A_GPIO_PORT_LOW->BSRR = PHASE_A_GPIO_LOW;
    PHASE_B_GPIO_PORT_LOW->BSRR = PHASE_B_GPIO_LOW;
    PHASE_C_GPIO_PORT_LOW->BSRR = PHASE_C_GPIO_LOW;
    DDL_GPIO_SetPinMode(PHASE_A_GPIO_PORT_LOW,PHASE_A_GPIO_LOW,DDL_GPIO_MODE_OUTPUT);
    DDL_GPIO_SetPinMode(PHASE_B_GPIO_PORT_LOW,PHASE_B_GPIO_LOW,DDL_GPIO_MODE_OUTPUT);
    DDL_GPIO_SetPinMode(PHASE_C_GPIO_PORT_LOW,PHASE_C_GPIO_LOW,DDL_GPIO_MODE_OUTPUT);
    DDL_GPIO_LockKey(GPIOA, DDL_GPIO_LOCK_ENABLE);
    DDL_GPIO_LockKey(GPIOA, DDL_GPIO_LOCK_ENABLE);
#endif
}
void phaseAPWM()
{
#if USE_FROCE_LEVEL
    if (!eepromBuffer.comp_pwm)
    {
        DDL_ATMR_CHAN_EnableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_AL);
        DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_AL,DDL_ATMR_FORCE_OUTPUT_AL_LOW);
    }
    else
    {
        DDL_ATMR_CHAN_DisableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_AL);
        DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_AL,DDL_ATMR_FORCE_OUTPUT_AL_LOW);
    }

    DDL_ATMR_CHAN_DisableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_AH);
    DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_AH,DDL_ATMR_FORCE_OUTPUT_AH_LOW);
#else
    DDL_GPIO_LockKey(GPIOA, DDL_GPIO_LOCK_DISABLE);
    PHASE_A_GPIO_PORT_LOW->BRR = PHASE_A_GPIO_LOW;
    DDL_GPIO_SetPinMode(PHASE_A_GPIO_PORT_LOW,PHASE_A_GPIO_LOW,DDL_GPIO_MODE_OUTPUT);
    
    DDL_GPIO_SetPinMode(PHASE_A_GPIO_PORT_HIGH,PHASE_A_GPIO_HIGH,DDL_GPIO_MODE_ALTERNATE);
    DDL_GPIO_LockKey(GPIOA, DDL_GPIO_LOCK_ENABLE);
#endif
}
void phaseBPWM()
{
#if USE_FROCE_LEVEL
    if (!eepromBuffer.comp_pwm)
    {
        DDL_ATMR_CHAN_EnableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_BL);
        DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_BL,DDL_ATMR_FORCE_OUTPUT_BL_LOW);
    }
    else
    {
        DDL_ATMR_CHAN_DisableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_BL);
        DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_BL,DDL_ATMR_FORCE_OUTPUT_BL_LOW);
    }
    DDL_ATMR_CHAN_DisableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_BH);
    DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_BH,DDL_ATMR_FORCE_OUTPUT_BH_LOW);
#else
    DDL_GPIO_LockKey(GPIOA, DDL_GPIO_LOCK_DISABLE);
    PHASE_B_GPIO_PORT_LOW->BRR = PHASE_B_GPIO_LOW;
    DDL_GPIO_SetPinMode(PHASE_B_GPIO_PORT_LOW,PHASE_B_GPIO_LOW,DDL_GPIO_MODE_OUTPUT);
    
    DDL_GPIO_SetPinMode(PHASE_B_GPIO_PORT_HIGH,PHASE_B_GPIO_HIGH,DDL_GPIO_MODE_ALTERNATE);
    DDL_GPIO_LockKey(GPIOA, DDL_GPIO_LOCK_ENABLE);    
#endif
}
void phaseCPWM()
{
#if USE_FROCE_LEVEL
    if (!eepromBuffer.comp_pwm)
    {
        DDL_ATMR_CHAN_EnableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_CL);
        DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_CL,DDL_ATMR_FORCE_OUTPUT_CL_LOW);
    }
    else
    {
        DDL_ATMR_CHAN_DisableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_CL);
        DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_CL,DDL_ATMR_FORCE_OUTPUT_CL_LOW);
    }
    DDL_ATMR_CHAN_DisableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_CH);
    DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_CH,DDL_ATMR_FORCE_OUTPUT_CH_LOW);
#else
    DDL_GPIO_LockKey(GPIOA, DDL_GPIO_LOCK_DISABLE);
    PHASE_C_GPIO_PORT_LOW->BRR = PHASE_C_GPIO_LOW;
    DDL_GPIO_SetPinMode(PHASE_C_GPIO_PORT_LOW,PHASE_C_GPIO_LOW,DDL_GPIO_MODE_OUTPUT);
    
    DDL_GPIO_SetPinMode(PHASE_C_GPIO_PORT_HIGH,PHASE_C_GPIO_HIGH,DDL_GPIO_MODE_ALTERNATE);
    DDL_GPIO_LockKey(GPIOA, DDL_GPIO_LOCK_ENABLE);
#endif
}
void phaseAFLOAT()
{
#if USE_FROCE_LEVEL
    DDL_ATMR_CHAN_EnableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_AH);
    DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_AH,DDL_ATMR_FORCE_OUTPUT_AH_LOW);
    DDL_ATMR_CHAN_EnableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_AL);
    DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_AL,DDL_ATMR_FORCE_OUTPUT_AL_LOW);
#else
    DDL_GPIO_LockKey(GPIOA, DDL_GPIO_LOCK_DISABLE);
    PHASE_A_GPIO_PORT_HIGH->BRR = PHASE_A_GPIO_HIGH;
    DDL_GPIO_SetPinMode(PHASE_A_GPIO_PORT_HIGH,PHASE_A_GPIO_HIGH,DDL_GPIO_MODE_OUTPUT);
    
    PHASE_A_GPIO_PORT_LOW->BRR = PHASE_A_GPIO_LOW;
    DDL_GPIO_SetPinMode(PHASE_A_GPIO_PORT_LOW,PHASE_A_GPIO_LOW,DDL_GPIO_MODE_OUTPUT);
    DDL_GPIO_LockKey(GPIOA, DDL_GPIO_LOCK_ENABLE);
#endif
}
void phaseBFLOAT()
{
#if USE_FROCE_LEVEL
    DDL_ATMR_CHAN_EnableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_BH);
    DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_BH,DDL_ATMR_FORCE_OUTPUT_BH_LOW);
    DDL_ATMR_CHAN_EnableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_BL);
    DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_BL,DDL_ATMR_FORCE_OUTPUT_BL_LOW);
#else
    DDL_GPIO_LockKey(GPIOA, DDL_GPIO_LOCK_DISABLE);
    PHASE_B_GPIO_PORT_HIGH->BRR = PHASE_B_GPIO_HIGH;
    DDL_GPIO_SetPinMode(PHASE_B_GPIO_PORT_HIGH,PHASE_B_GPIO_HIGH,DDL_GPIO_MODE_OUTPUT);
    
    PHASE_B_GPIO_PORT_LOW->BRR = PHASE_B_GPIO_LOW;
    DDL_GPIO_SetPinMode(PHASE_B_GPIO_PORT_LOW,PHASE_B_GPIO_LOW,DDL_GPIO_MODE_OUTPUT);
    DDL_GPIO_LockKey(GPIOA, DDL_GPIO_LOCK_ENABLE);
#endif
}
void phaseCFLOAT()
{
#if USE_FROCE_LEVEL
    DDL_ATMR_CHAN_EnableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_CH);
    DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_CH,DDL_ATMR_FORCE_OUTPUT_CH_LOW);
    DDL_ATMR_CHAN_EnableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_CL);
    DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_CL,DDL_ATMR_FORCE_OUTPUT_CL_LOW);
#else
    DDL_GPIO_LockKey(GPIOA, DDL_GPIO_LOCK_DISABLE);
    PHASE_C_GPIO_PORT_HIGH->BRR = PHASE_C_GPIO_HIGH;
    DDL_GPIO_SetPinMode(PHASE_C_GPIO_PORT_HIGH,PHASE_C_GPIO_HIGH,DDL_GPIO_MODE_OUTPUT);
    
    PHASE_C_GPIO_PORT_LOW->BRR = PHASE_C_GPIO_LOW;
    DDL_GPIO_SetPinMode(PHASE_C_GPIO_PORT_LOW,PHASE_C_GPIO_LOW,DDL_GPIO_MODE_OUTPUT);
    DDL_GPIO_LockKey(GPIOA, DDL_GPIO_LOCK_ENABLE);
#endif
}

void phaseALOW()
{
#if USE_FROCE_LEVEL
    DDL_ATMR_CHAN_EnableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_AH);
    DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_AH,DDL_ATMR_FORCE_OUTPUT_AH_LOW);
    DDL_ATMR_CHAN_EnableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_AL);
    DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_AL,DDL_ATMR_FORCE_OUTPUT_AL_HIGH);
#else
    DDL_GPIO_LockKey(GPIOA, DDL_GPIO_LOCK_DISABLE);
    PHASE_A_GPIO_PORT_HIGH->BRR = PHASE_A_GPIO_HIGH;
    DDL_GPIO_SetPinMode(PHASE_A_GPIO_PORT_HIGH,PHASE_A_GPIO_HIGH,DDL_GPIO_MODE_OUTPUT);
    
    PHASE_A_GPIO_PORT_LOW->BSRR = PHASE_A_GPIO_LOW;
    DDL_GPIO_SetPinMode(PHASE_A_GPIO_PORT_LOW,PHASE_A_GPIO_LOW,DDL_GPIO_MODE_OUTPUT);
    DDL_GPIO_LockKey(GPIOA, DDL_GPIO_LOCK_ENABLE);
#endif
}
void phaseBLOW()
{
#if USE_FROCE_LEVEL
    DDL_ATMR_CHAN_EnableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_BH);
    DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_BH,DDL_ATMR_FORCE_OUTPUT_BH_LOW);
    DDL_ATMR_CHAN_EnableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_BL);
    DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_BL,DDL_ATMR_FORCE_OUTPUT_BL_HIGH);
#else
    DDL_GPIO_LockKey(GPIOA, DDL_GPIO_LOCK_DISABLE);
    PHASE_B_GPIO_PORT_HIGH->BRR = PHASE_B_GPIO_HIGH;
    DDL_GPIO_SetPinMode(PHASE_B_GPIO_PORT_HIGH,PHASE_B_GPIO_HIGH,DDL_GPIO_MODE_OUTPUT);
    
    PHASE_B_GPIO_PORT_LOW->BSRR = PHASE_B_GPIO_LOW;
    DDL_GPIO_SetPinMode(PHASE_B_GPIO_PORT_LOW,PHASE_B_GPIO_LOW,DDL_GPIO_MODE_OUTPUT);
    DDL_GPIO_LockKey(GPIOA, DDL_GPIO_LOCK_ENABLE);
#endif
}
void phaseCLOW()
{
#if USE_FROCE_LEVEL
    DDL_ATMR_CHAN_EnableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_CH);
    DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_CH,DDL_ATMR_FORCE_OUTPUT_CH_LOW);
    DDL_ATMR_CHAN_EnableForceOutput(ATMR,DDL_ATMR_FORCE_OUTPUT_CL);
    DDL_ATMR_CHAN_SetForceOutputValue(ATMR,DDL_ATMR_FORCE_OUTPUT_CL,DDL_ATMR_FORCE_OUTPUT_CL_HIGH);
#else
    DDL_GPIO_LockKey(GPIOA, DDL_GPIO_LOCK_DISABLE);
    PHASE_C_GPIO_PORT_HIGH->BRR = PHASE_C_GPIO_HIGH;
    DDL_GPIO_SetPinMode(PHASE_C_GPIO_PORT_HIGH,PHASE_C_GPIO_HIGH,DDL_GPIO_MODE_OUTPUT);
    
    PHASE_C_GPIO_PORT_LOW->BSRR = PHASE_C_GPIO_LOW;
    DDL_GPIO_SetPinMode(PHASE_C_GPIO_PORT_LOW,PHASE_C_GPIO_LOW,DDL_GPIO_MODE_OUTPUT);
    DDL_GPIO_LockKey(GPIOA, DDL_GPIO_LOCK_ENABLE);
#endif
}
void allOff()
{
    phaseAFLOAT();
    phaseBFLOAT();
    phaseCFLOAT();
}
// full braking shorting all low sides
void fullBrake()
{
    phaseALOW();
    phaseBLOW();
    phaseCLOW();
}
// for stepper_sine
void allpwm()
{
    phaseAPWM();
    phaseBPWM();
    phaseCPWM();
}

void twoChannelForward()
{
    phaseAPWM();
    phaseBLOW();
    phaseCPWM();
}

void twoChannelReverse()
{
    phaseALOW();
    phaseBPWM();
    phaseCLOW();
}

void comStep(int newStep)
{
    switch (newStep) 
    {
        case 1: // A-B
            phaseCFLOAT();
            phaseBLOW();
            phaseAPWM();
            break;

        case 2: // C-B
            phaseAFLOAT();
            phaseBLOW();
            phaseCPWM();
            break;

        case 3: // C-A
            phaseBFLOAT();
            phaseALOW();
            phaseCPWM();
            break;

        case 4: // B-A
            phaseCFLOAT();
            phaseALOW();
            phaseBPWM();
            break;

        case 5: // B-C
            phaseAFLOAT();
            phaseCLOW();
            phaseBPWM();
            break;

        case 6: // A-C
            phaseBFLOAT();
            phaseCLOW();
            phaseAPWM();
            break;
    }
}